#include "openplc_cfi.h"
#define CFI_PROTECT 1
/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

#include "accessor.h"

#include "POUS.h"

// CONFIGURATION CONFIG0

void RES0_init__(void);

void config_init__(void) {
  #if CFI_PROTECT
  /* CFI: matiec_generated, tag=0xA6FE85BBU */
  CFI_PROLOGUE_TAG(0xA6FE85BBU);
  #endif

  BOOL retain;
  retain = 0;
  
  RES0_init__();
  #if CFI_PROTECT
  CFI_EPILOGUE_TAG_PAC(0xA6FE85BBU);
  #endif
}

void RES0_run__(unsigned long tick);

void config_run__(unsigned long tick) {
  #if CFI_PROTECT
  /* CFI: matiec_generated, tag=0x86B40AFCU */
  CFI_PROLOGUE_TAG(0x86B40AFCU);
  #endif

  RES0_run__(tick);
  #if CFI_PROTECT
  CFI_EPILOGUE_TAG_PAC(0x86B40AFCU);
  #endif
}
unsigned long long common_ticktime__ = 200000000ULL * 1ULL; /*ns*/
unsigned long greatest_tick_count__ = (unsigned long)0UL; /*tick*/
