#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM PROGRAM0
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(BOOL,VALVE_IN_INPUT)
  __DECLARE_VAR(BOOL,VALVE_OUT_INPUT)

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_VAR(BOOL,VALVE_IN)
  __DECLARE_VAR(BOOL,VALVE_OUT)
  __DECLARE_EXTERNAL(REAL,WATER_HEIGHT)
  __DECLARE_VAR(REAL,WATER_HEIGH_MIN)
  __DECLARE_VAR(REAL,WATER_HEIGHT_MAX)
  __DECLARE_VAR(REAL,INNER_WATER_HEIGHT)
  __DECLARE_EXTERNAL(REAL,VALVE_IN_RATE)
  __DECLARE_VAR(REAL,VALVE_IN_RATE_MIN)
  __DECLARE_VAR(REAL,VALVE_IN_RATE_MAX)
  __DECLARE_VAR(REAL,INNER_VALVE_IN_RATE)
  __DECLARE_VAR(REAL,VALVE_OUT_RATE)
  __DECLARE_VAR(REAL,_TMP_BOOL_TO_REAL41_OUT)
  __DECLARE_VAR(REAL,_TMP_MUL17_OUT)
  __DECLARE_VAR(REAL,_TMP_ADD40_OUT)
  __DECLARE_VAR(REAL,_TMP_BOOL_TO_REAL12_OUT)
  __DECLARE_VAR(REAL,_TMP_MUL23_OUT)
  __DECLARE_VAR(REAL,_TMP_SQRT51_OUT)
  __DECLARE_VAR(REAL,_TMP_MUL27_OUT)
  __DECLARE_VAR(REAL,_TMP_SUB22_OUT)
  __DECLARE_VAR(REAL,_TMP_LIMIT52_OUT)
  __DECLARE_VAR(REAL,_TMP_LIMIT14_OUT)

} PROGRAM0;

void PROGRAM0_init__(PROGRAM0 *data__, BOOL retain);
// Code part
void PROGRAM0_body__(PROGRAM0 *data__);
// PROGRAM PROGRAM1
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables
  __DECLARE_VAR(REAL,SETPOINT)

  // PROGRAM private variables - TEMP, private and located variables
  PID PID0;
  __DECLARE_VAR(BOOL,PID_AUTO)
  __DECLARE_VAR(REAL,PID_X0)
  __DECLARE_VAR(REAL,PID_KP)
  __DECLARE_VAR(REAL,PID_TR)
  __DECLARE_VAR(REAL,PID_TD)
  __DECLARE_VAR(TIME,PID_CYCLE)
  __DECLARE_EXTERNAL(REAL,WATER_HEIGHT)
  __DECLARE_EXTERNAL(REAL,VALVE_IN_RATE)

} PROGRAM1;

void PROGRAM1_init__(PROGRAM1 *data__, BOOL retain);
// Code part
void PROGRAM1_body__(PROGRAM1 *data__);
#endif //__POUS_H
