#include "openplc_cfi.h"
#define CFI_PROTECT 1
/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE RES0

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "Config0.h"
__DECLARE_GLOBAL(REAL,RES0,WATER_HEIGHT)
__DECLARE_GLOBAL(REAL,RES0,VALVE_IN_RATE)

#include "POUS.c"

BOOL TASK0;
BOOL TASK1;
PROGRAM0 RES0__INSTANCE0;
#define INSTANCE0 RES0__INSTANCE0
PROGRAM1 RES0__INSTANCE1;
#define INSTANCE1 RES0__INSTANCE1

void RES0_init__(void) {
  #if CFI_PROTECT
  /* CFI: matiec_generated, tag=0xE79FE9C1U */
  CFI_PROLOGUE_TAG(0xE79FE9C1U);
  #endif

  BOOL retain;
  retain = 0;
  __INIT_GLOBAL(REAL,WATER_HEIGHT,__INITIAL_VALUE(100.0),retain)
  __INIT_GLOBAL(REAL,VALVE_IN_RATE,__INITIAL_VALUE(0.0),retain)
  TASK0 = __BOOL_LITERAL(FALSE);
  TASK1 = __BOOL_LITERAL(FALSE);
  PROGRAM0_init__(&INSTANCE0,retain);
  PROGRAM1_init__(&INSTANCE1,retain);
  #if CFI_PROTECT
  CFI_EPILOGUE_TAG_PAC(0xE79FE9C1U);
  #endif
}

void RES0_run__(unsigned long tick) {
  #if CFI_PROTECT
  /* CFI: matiec_generated, tag=0xE7C002AFU */
  CFI_PROLOGUE_TAG(0xE7C002AFU);
  #endif

  TASK0 = !(tick % 1);
  TASK1 = !(tick % 1);
  if (TASK0) {
    PROGRAM0_body__(&INSTANCE0);
  }
  if (TASK1) {
    PROGRAM1_body__(&INSTANCE1);
  }
  #if CFI_PROTECT
  CFI_EPILOGUE_TAG_PAC(0xE7C002AFU);
  #endif
}

